version: '3.8'

services:
  frontend:
    image: szumiik/magazynex-frontend:latest
    
    ports:
      - "4200:80"
    environment:
      - API_URL=http://localhost:8080/api
    restart: unless-stopped